Clarify Flow Segment in README
bbc/tams pull request #23
Opened 2024-02-05 16:49 UTC by GeorginaShippey

# Details
Reduce use of the term 'segment' in favor of Flow Segment.

# Pivotal Story (if relevant)
Story URL: https://www.pivotaltracker.com/n/projects/2147543/stories/186876593

# Related PRs
_Where appropriate. Indicate order to be merged._

# Submitter PR Checks
_(tick as appropriate)_

- [ ] PR completes task/fixes bug
- [ ] API version has been incremented if necessary
- [ ] ADR status has been updated, and ADR implementation has been recorded
- [ ] Documentation updated (README, etc.)
- [ ] PR added to Pivotal story (if relevant)
- [ ] Follow-up stories added to Pivotal

# Reviewer PR Checks
_(tick as appropriate)_

- [ ] PR completes task/fixes bug
- [ ] Design makes sense, and fits with our current code base
- [ ] Code is easy to follow
- [ ] PR size is sensible
- [ ] Commit history is sensible and tidy

# Info on PRs
The checks above are guidelines. They don't all have to be ticked, but they should all have been considered.

2024-02-05 16:51 UTC, GeorginaShippey commented
I changed some usages of FlowSegment to Flow Segment - any thoughts on that? I think we are generally interested in Flow Segments as a concept rather than an implementation.

Also use of 'media data' or 'grain media data' to talk about the content being stored in the media objects. Any opinions on the best wording - or even if its just best to use the word grain.

2024-02-06 11:27 UTC, GeorginaShippey commented on README.md
> +We refer to grain metadata stored in the object store as 'media objects'.
Fix: grain metadata -> grain media data

2024-02-06 12:11 UTC, AndrewGibb requested changes
A few suggested changes. Let me know what you think.

2024-02-06 12:11 UTC, AndrewGibb commented on README.md
> +3. Store responds with a list of Flow Segment timeranges and URLs to PUT media data into, along with an optional `pre` URL to call before writing
This is OK for now, but will need revisiting after Sam has made his diagrams about Segments, and we've properly shaken down the questions around fixed-size segments. I'll pop in another ticket for that.

2024-02-09 09:47 UTC, samdbmg commented
Changes LGTM, barring Andy's notes

2024-02-09 10:28 UTC, AndrewGibb approved these changes
LGTM

2024-02-09 10:34 UTC, merged